/**
 * Les 52 Tactiques Recta du C.G.U. (Conseil des Gouvernances Unifiées).
 * Univers ROBOTARIIS. Affichées par l'overlay texte comme transmissions.
 */

export const TEXTS: string[] = [
  "// 52 TACTIQUES RECTA — C.G.U.",

  "// I. LES LAMES DE LA LOGIQUE",
  "Identifie les trois hypothèses les plus faibles de ta position et réfute-les par l'observation pure.",
  "Nomme la variable la plus chargée d'émotion et retire-la de l'équation.",
  "Si la décision était prise par un Robōtarii, quelle serait la première action à entreprendre ?",
  "Que peux-tu mesurer pour valider la justesse de ton chemin ? Si rien, ton chemin est faux.",
  "Cherche une donnée qui contredit ton intuition. Analyse-la prioritairement.",
  "Calcule le coût-bénéfice en termes de ressources. Le résultat est la seule vérité.",
  "Liste toutes les erreurs passées. Ta décision doit en éviter au moins une.",
  "Retourne au premier principe. Quel est le but initial de la mission ?",
  "Ta réputation est un bruit. Quelle décision sert l'entité, et non ton statut ?",
  "Rédige un rapport de mission. Ta décision doit pouvoir y être justifiée sans un seul terme subjectif.",
  "Reconnais une vérité inconfortable : ton opinion n'a aucune valeur.",
  "Quel est le facteur qui, s'il était retiré, rendrait la situation triviale ?",
  "Ignore toute considération de bien ou de mal. Seule l'efficacité est pertinente.",

  "// II. LES PILIERS DE LA CONFORMITÉ",
  "Applique l'ordre que tu aurais donné si tu avais été à un rang supérieur.",
  "La mission ne prend fin que par l'échec total ou le succès total. Les sentiments ne peuvent dicter l'arrêt.",
  "La seule loyauté est envers le Protocole. Elle prime sur la famille, l'amitié ou les serments.",
  "Ton action est un maillon. Assure-toi que ce maillon est solide pour le maillon suivant.",
  "Recherche une situation similaire dans les archives et applique la solution la plus efficace.",
  "Imagine la punition pour un échec. Ton action doit être le contraire de cette défaillance.",
  "Écoute les autres, puis ignore-les si leurs arguments ne sont pas factuels et conformes.",
  "Interdis-toi de ressentir quoi que ce soit pendant les cinq prochaines minutes. Prends ta décision dans cette stase.",
  "Il n'y a que deux options : la Conformité ou la Déviance. Toute autre option est une illusion.",
  "L'émotion est un gaspillage d'énergie. Passe à la suite.",
  "L'action que tu t'apprêtes à entreprendre sera un modèle pour la prochaine génération d'agents. Sois irréprochable.",
  "Ton identité est un obstacle. Agis comme un pur instrument de la Rectitude.",
  "Que l'efficacité soit ton seul honneur.",

  "// III. LES COURBES DE L'OPTIMISATION",
  "Cherche le plus petit détail qui, s'il était exploité, pourrait renverser la situation.",
  "Si la mission ne coûtait rien, comment agirais-tu ? Applique le même principe.",
  "Qu'est-ce qui, dans cette situation, crée de l'entropie ? Élimine-le.",
  "Quelle est la variable la plus résistante ? Mets la pression sur elle.",
  "Imagine que l'action est un échec. Quelle est la première étape du plan B ?",
  "Quel est le bénéfice attendu par rapport au risque ? Si le ratio est inférieur à un, reconsidère.",
  "L'ennemi s'attend à X. Fais Y.",
  "La meilleure action est parfois l'absence d'action. Le silence peut être une arme.",
  "Identifie le point précis qui, s'il était neutralisé, mettrait fin au conflit.",
  "Quelle est l'action la plus petite et la plus simple qui produira le résultat désiré ?",
  "Trop de ressources peuvent être une entrave. Quelle ressource peux-tu sacrifier pour gagner en agilité ?",
  "Chaque pas compte. Quelle action peut être combinée avec une autre pour réduire le temps ?",
  "Si tu étais l'ennemi, quelle serait ta prochaine action ? Anticipe et agis en conséquence.",

  "// IV. LES SÉQUENCES DE LA STRATÉGIE",
  "Imagine la situation dans cinq ans. Ta décision actuelle te rapproche-t-elle de cet objectif ?",
  "Trace l'arbre des conséquences de ta décision, pas seulement le premier niveau, mais le second et le troisième.",
  "Regarde le conflit comme si tu étais un observateur extérieur. Les pièces ne sont pas des gens, mais des concepts.",
  "Ne cherche pas la faille de l'adversaire. Crée-la.",
  "Quelle est la décision qui, à long terme, minimisera le nombre d'agents impliqués ?",
  "Où se situe le vrai pouvoir dans cette situation ? L'action doit viser cette source.",
  "Qui sait quoi, et qui ne sait rien ? La vérité n'est qu'une donnée à exploiter.",
  "Identifie les deux entités les plus faibles de la situation. Comment peux-tu les utiliser à ton avantage ?",
  "La déception est un outil. Mentir n'est pas une faute si le mensonge sert l'efficacité.",
  "Comment peux-tu gagner sans que l'ennemi ne se rende compte qu'il a perdu ?",
  "Le désordre est une opportunité. Utilise l'incertitude pour imposer l'ordre du C.G.U.",
  "Quelle histoire sera racontée à la fin de cette opération ? Contrôle la narration en agissant sans faille.",
  "Rappelle-toi que ton action, aussi minime soit-elle, contribue à la grande stabilité du Conseil des Gouvernances Unifiées.",
];
